CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO=n

# deep sleep, default = 15 minutes
# does not work for me, keyboard doesn't want to wake up
CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# soft-off, wake-up only with HW reset button
# CONFIG_ZMK_PM_SOFT_OFF=y

# enable mouse control
CONFIG_ZMK_POINTING=y


# enabling these 3 options with ZMK studio fails the build
CONFIG_ZMK_USB_LOGGING=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n

# DC-DC enabled by default has lower consumption than LDO
#CONFIG_BOARD_ENABLE_DCDC=n
