CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO=y

# deep sleep, default = 15 minutes
CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# soft-off, wake-up only with HW reset button
# CONFIG_ZMK_PM_SOFT_OFF=y

# enable mouse control
CONFIG_ZMK_POINTING=y

#CONFIG_ZMK_USB_LOGGING=n
#CONFIG_SERIAL=n
#CONFIG_UART_CONSOLE=n

#CONFIG_BOARD_ENABLE_DCDC=n
